{
  pkgs,
  pkgs-unstable,
  ...
}: {
  home.packages = with pkgs; [
    conftest
    devenv
    gcc
    gnumake
    pkgs-unstable.go
    (pkgs-unstable.google-cloud-sdk.withExtraComponents [google-cloud-sdk.components.gke-gcloud-auth-plugin])
    kubectl
    kubectx
    kubernetes-helm
    (wrapHelm kubernetes-helm {
      plugins = with kubernetes-helmPlugins; [
        helm-diff
        helm-secrets
      ];
    })
    openssl_1_1
    pkgs-unstable.ansible-lint
    pkgs-unstable.bun
    pkgs-unstable.libpq
    pkgs-unstable.llm
    pkgs-unstable.node-gyp
    pkgs-unstable.nodejs_20
    pkgs-unstable.terraform
    postgresql_16
    pixman
    prometheus.cli
    docker-client
    python310
    texliveBasic
    pixman
    wrangler
    uv
    dos2unix
    csvkit
    cairo
    pango
    libjpeg
    libpng
    libpng
    librsvg
    giflib
    pkg-config
    poetry
    regal
    rustc
    rustup
    scc
    pkgs-unstable.sops
    terragrunt
    terraform-ls
    tflint
    tfsec
    podman
    fd
    k9s
    phpactor
    php
    php84Packages.composer
    golangci-lint
    nmap
    hugo
    mkcert
    maple-mono.truetype
    maple-mono.NF-unhinted
  ];
}
